# Generated by Django 4.2.2 on 2024-01-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscart', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_addbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
