# Generated by Django 4.2.2 on 2024-01-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookscart', '0003_admin_addbooks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_addbooks',
            old_name='image',
            new_name='photo',
        ),
    ]
