# Generated by Django 4.2.2 on 2024-01-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscart', '0007_delete_buynow'),
    ]

    operations = [
        migrations.CreateModel(
            name='buynow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
