# Generated by Django 4.2.2 on 2024-01-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscart', '0008_buynow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buynow',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
