# Generated by Django 4.2.2 on 2024-02-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookscart', '0010_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
