# Generated by Django 4.2.2 on 2024-02-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookscart', '0012_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
