# Generated by Django 5.0.3 on 2024-03-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscart', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_addbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
