# Generated by Django 5.0.3 on 2024-03-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscart', '0018_buynow'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('book_id', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
